[2025-05-02T02:57:11.455+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T02:57:11.470+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T02:57:11.477+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T02:57:11.478+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-02T02:57:11.488+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-05-01 02:30:00+00:00
[2025-05-02T02:57:11.498+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9836) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T02:57:11.503+0000] {standard_task_runner.py:72} INFO - Started process 9866 to run task
[2025-05-02T02:57:11.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_api_etl', 'load_sentiment_data_to_snowflake', 'scheduled__2025-05-01T02:30:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmp9rim2i8g']
[2025-05-02T02:57:11.514+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask load_sentiment_data_to_snowflake
[2025-05-02T02:57:11.621+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [running]> on host d110dddef273
[2025-05-02T02:57:11.717+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_api_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T02:30:00+00:00'
[2025-05-02T02:57:11.720+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T02:57:11.732+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-02T02:57:11.734+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-02T02:57:11.736+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-02T02:57:11.736+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-02T02:57:13.786+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T02:57:13.976+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T03:05:47.749+0000] {job.py:229} INFO - Heartbeat recovered after 490.90 seconds
[2025-05-02T04:06:50.223+0000] {job.py:229} INFO - Heartbeat recovered after 3637.14 seconds
[2025-05-02T05:08:09.341+0000] {job.py:229} INFO - Heartbeat recovered after 3623.16 seconds
[2025-05-02T05:09:28.625+0000] {job.py:229} INFO - Heartbeat recovered after 58.94 seconds
[2025-05-02T05:09:38.781+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-02T05:09:38.788+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-02T05:09:38.791+0000] {process_utils.py:132} INFO - Sending 15 to group 9866. PIDs of all processes in the group: [9866]
[2025-05-02T05:09:38.791+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 9866
[2025-05-02T05:09:38.792+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-02T05:09:38.827+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-02T05:09:38.898+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=9866, status='terminated', exitcode=0, started='02:57:11') (9866) terminated with exit code 0
[2025-05-02T22:02:49.574+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T22:02:49.599+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T22:02:49.607+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [queued]>
[2025-05-02T22:02:49.607+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-02T22:02:49.624+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-05-01 02:30:00+00:00
[2025-05-02T22:02:49.641+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=575) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T22:02:49.644+0000] {standard_task_runner.py:72} INFO - Started process 591 to run task
[2025-05-02T22:02:49.642+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_api_etl', 'load_sentiment_data_to_snowflake', 'scheduled__2025-05-01T02:30:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl_api.py', '--cfg-path', '/tmp/tmp4q9zrv6b']
[2025-05-02T22:02:49.651+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask load_sentiment_data_to_snowflake
[2025-05-02T22:02:49.745+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_api_etl.load_sentiment_data_to_snowflake scheduled__2025-05-01T02:30:00+00:00 [running]> on host edac5e2fb0a3
[2025-05-02T22:02:49.878+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_api_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T02:30:00+00:00'
[2025-05-02T22:02:49.883+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T22:02:49.914+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-02T22:02:49.920+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-02T22:02:49.926+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-02T22:02:49.928+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-02T22:02:51.466+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-02T22:02:51.579+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
